#!/bin/sh
# SPDX-FileCopyrightText: 2014- GitHub, Inc. and Git LFS contributors
# SPDX-License-Identifier: MIT
# Full license: LICENSES/MIT.txt (repository root)

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path.\n"; exit 2; }
git lfs post-commit "$@"
